line_length: 240 # Max line length before warning (default is 120)

disabled_rules:
  - trailing_whitespace # Disables SwiftLint complaining about whitespace characters on empty lines
  - todo # Disables auto-warning of TODO statements

included:
  - ../Hyperspace

excluded:
  - Pods # Don't lint anything coming in through Cocoapods

identifier_name:
  excluded:
    - id
    - ok
