# Set max line length before warning (default is 120)
line_length: 240

disabled_rules:
  - type_name
  - trailing_whitespace
  - force_try
  - force_cast
  - todo
  - statement_position

identifier_name:
  excluded:
    - id
    - ok

excluded:
  - Carthage
