# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: swift
before_install:
  - gem install cocoapods --pre # Since Travis is not always on latest version
  - pod install --project-directory=Example
script:
  - set -o pipefail

  - xcodebuild test -workspace Example/Hyperspace.xcworkspace -scheme Hyperspace-Example -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.2,name=iPhone X" | xcpretty
  - xcodebuild test -workspace Example/Hyperspace.xcworkspace -scheme Hyperspace_Example_tvOS -sdk appletvsimulator -destination "platform=tvOS Simulator,OS=11.2,name=Apple TV 4K" | xcpretty
  - xcodebuild build -workspace Example/Hyperspace.xcworkspace -scheme Hyperspace_Example_watchOS -sdk watchsimulator | xcpretty

  - pod lib lint
