# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: swift
before_install:
  - gem install cocoapods --pre # Since Travis is not always on latest version
  - pod install --project-directory=Example
script:
  - set -o pipefail

  - xcodebuild build -workspace Example/Hyperspace.xcworkspace -scheme "Hyperspace_Example_watchOS (Notification)" -sdk watchsimulator | xcpretty

  - pod lib lint
